/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.example.model.avaliacao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AvaliacaoDetalhe service. Represents a row in the &quot;DESAFIO_AvaliacaoDetalhe&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.example.model.avaliacao.model.impl.AvaliacaoDetalheModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.example.model.avaliacao.model.impl.AvaliacaoDetalheImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AvaliacaoDetalhe
 * @generated
 */
@ProviderType
public interface AvaliacaoDetalheModel
	extends BaseModel<AvaliacaoDetalhe>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a avaliacao detalhe model instance should use the {@link AvaliacaoDetalhe} interface instead.
	 */

	/**
	 * Returns the primary key of this avaliacao detalhe.
	 *
	 * @return the primary key of this avaliacao detalhe
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this avaliacao detalhe.
	 *
	 * @param primaryKey the primary key of this avaliacao detalhe
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company ID of this avaliacao detalhe.
	 *
	 * @return the company ID of this avaliacao detalhe
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this avaliacao detalhe.
	 *
	 * @param companyId the company ID of this avaliacao detalhe
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this avaliacao detalhe.
	 *
	 * @return the group ID of this avaliacao detalhe
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this avaliacao detalhe.
	 *
	 * @param groupId the group ID of this avaliacao detalhe
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this avaliacao detalhe.
	 *
	 * @return the user ID of this avaliacao detalhe
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this avaliacao detalhe.
	 *
	 * @param userId the user ID of this avaliacao detalhe
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this avaliacao detalhe.
	 *
	 * @return the user uuid of this avaliacao detalhe
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this avaliacao detalhe.
	 *
	 * @param userUuid the user uuid of this avaliacao detalhe
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this avaliacao detalhe.
	 *
	 * @return the create date of this avaliacao detalhe
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this avaliacao detalhe.
	 *
	 * @param createDate the create date of this avaliacao detalhe
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this avaliacao detalhe.
	 *
	 * @return the modified date of this avaliacao detalhe
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this avaliacao detalhe.
	 *
	 * @param modifiedDate the modified date of this avaliacao detalhe
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the avaliacao detalhe ID of this avaliacao detalhe.
	 *
	 * @return the avaliacao detalhe ID of this avaliacao detalhe
	 */
	public long getAvaliacaoDetalheId();

	/**
	 * Sets the avaliacao detalhe ID of this avaliacao detalhe.
	 *
	 * @param avaliacaoDetalheId the avaliacao detalhe ID of this avaliacao detalhe
	 */
	public void setAvaliacaoDetalheId(long avaliacaoDetalheId);

	/**
	 * Returns the avaliacao ID of this avaliacao detalhe.
	 *
	 * @return the avaliacao ID of this avaliacao detalhe
	 */
	public long getAvaliacaoId();

	/**
	 * Sets the avaliacao ID of this avaliacao detalhe.
	 *
	 * @param avaliacaoId the avaliacao ID of this avaliacao detalhe
	 */
	public void setAvaliacaoId(long avaliacaoId);

	/**
	 * Returns the tipo avaliador of this avaliacao detalhe.
	 *
	 * @return the tipo avaliador of this avaliacao detalhe
	 */
	public int getTipoAvaliador();

	/**
	 * Sets the tipo avaliador of this avaliacao detalhe.
	 *
	 * @param tipoAvaliador the tipo avaliador of this avaliacao detalhe
	 */
	public void setTipoAvaliador(int tipoAvaliador);

	/**
	 * Returns the nome avaliador of this avaliacao detalhe.
	 *
	 * @return the nome avaliador of this avaliacao detalhe
	 */
	@AutoEscape
	public String getNomeAvaliador();

	/**
	 * Sets the nome avaliador of this avaliacao detalhe.
	 *
	 * @param nomeAvaliador the nome avaliador of this avaliacao detalhe
	 */
	public void setNomeAvaliador(String nomeAvaliador);

	/**
	 * Returns the observacoes avaliador of this avaliacao detalhe.
	 *
	 * @return the observacoes avaliador of this avaliacao detalhe
	 */
	@AutoEscape
	public String getObservacoesAvaliador();

	/**
	 * Sets the observacoes avaliador of this avaliacao detalhe.
	 *
	 * @param observacoesAvaliador the observacoes avaliador of this avaliacao detalhe
	 */
	public void setObservacoesAvaliador(String observacoesAvaliador);

	/**
	 * Returns the desempenho of this avaliacao detalhe.
	 *
	 * @return the desempenho of this avaliacao detalhe
	 */
	public int getDesempenho();

	/**
	 * Sets the desempenho of this avaliacao detalhe.
	 *
	 * @param desempenho the desempenho of this avaliacao detalhe
	 */
	public void setDesempenho(int desempenho);

	@Override
	public AvaliacaoDetalhe cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}