/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.example.model.avaliacao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Avaliacao service. Represents a row in the &quot;DESAFIO_Avaliacao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.example.model.avaliacao.model.impl.AvaliacaoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.example.model.avaliacao.model.impl.AvaliacaoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Avaliacao
 * @generated
 */
@ProviderType
public interface AvaliacaoModel
	extends BaseModel<Avaliacao>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a avaliacao model instance should use the {@link Avaliacao} interface instead.
	 */

	/**
	 * Returns the primary key of this avaliacao.
	 *
	 * @return the primary key of this avaliacao
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this avaliacao.
	 *
	 * @param primaryKey the primary key of this avaliacao
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company ID of this avaliacao.
	 *
	 * @return the company ID of this avaliacao
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this avaliacao.
	 *
	 * @param companyId the company ID of this avaliacao
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this avaliacao.
	 *
	 * @return the group ID of this avaliacao
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this avaliacao.
	 *
	 * @param groupId the group ID of this avaliacao
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this avaliacao.
	 *
	 * @return the user ID of this avaliacao
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this avaliacao.
	 *
	 * @param userId the user ID of this avaliacao
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this avaliacao.
	 *
	 * @return the user uuid of this avaliacao
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this avaliacao.
	 *
	 * @param userUuid the user uuid of this avaliacao
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this avaliacao.
	 *
	 * @return the user name of this avaliacao
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this avaliacao.
	 *
	 * @param userName the user name of this avaliacao
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this avaliacao.
	 *
	 * @return the create date of this avaliacao
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this avaliacao.
	 *
	 * @param createDate the create date of this avaliacao
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this avaliacao.
	 *
	 * @return the modified date of this avaliacao
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this avaliacao.
	 *
	 * @param modifiedDate the modified date of this avaliacao
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the avaliacao ID of this avaliacao.
	 *
	 * @return the avaliacao ID of this avaliacao
	 */
	public long getAvaliacaoId();

	/**
	 * Sets the avaliacao ID of this avaliacao.
	 *
	 * @param avaliacaoId the avaliacao ID of this avaliacao
	 */
	public void setAvaliacaoId(long avaliacaoId);

	/**
	 * Returns the funcionario ID of this avaliacao.
	 *
	 * @return the funcionario ID of this avaliacao
	 */
	public long getFuncionarioId();

	/**
	 * Sets the funcionario ID of this avaliacao.
	 *
	 * @param funcionarioId the funcionario ID of this avaliacao
	 */
	public void setFuncionarioId(long funcionarioId);

	/**
	 * Returns the data avaliacao of this avaliacao.
	 *
	 * @return the data avaliacao of this avaliacao
	 */
	public Date getDataAvaliacao();

	/**
	 * Sets the data avaliacao of this avaliacao.
	 *
	 * @param dataAvaliacao the data avaliacao of this avaliacao
	 */
	public void setDataAvaliacao(Date dataAvaliacao);

	/**
	 * Returns the periodo desafio of this avaliacao.
	 *
	 * @return the periodo desafio of this avaliacao
	 */
	public int getPeriodoDesafio();

	/**
	 * Sets the periodo desafio of this avaliacao.
	 *
	 * @param periodoDesafio the periodo desafio of this avaliacao
	 */
	public void setPeriodoDesafio(int periodoDesafio);

	/**
	 * Returns the observacoes gerais of this avaliacao.
	 *
	 * @return the observacoes gerais of this avaliacao
	 */
	@AutoEscape
	public String getObservacoesGerais();

	/**
	 * Sets the observacoes gerais of this avaliacao.
	 *
	 * @param observacoesGerais the observacoes gerais of this avaliacao
	 */
	public void setObservacoesGerais(String observacoesGerais);

	/**
	 * Returns the area atuacao of this avaliacao.
	 *
	 * @return the area atuacao of this avaliacao
	 */
	public int getAreaAtuacao();

	/**
	 * Sets the area atuacao of this avaliacao.
	 *
	 * @param areaAtuacao the area atuacao of this avaliacao
	 */
	public void setAreaAtuacao(int areaAtuacao);

	@Override
	public Avaliacao cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}