/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.example.model.avaliacao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Avaliacoes service. Represents a row in the &quot;FOO_Avaliacoes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.example.model.avaliacao.model.impl.AvaliacoesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.example.model.avaliacao.model.impl.AvaliacoesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Avaliacoes
 * @generated
 */
@ProviderType
public interface AvaliacoesModel extends BaseModel<Avaliacoes>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a avaliacoes model instance should use the {@link Avaliacoes} interface instead.
	 */

	/**
	 * Returns the primary key of this avaliacoes.
	 *
	 * @return the primary key of this avaliacoes
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this avaliacoes.
	 *
	 * @param primaryKey the primary key of this avaliacoes
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company ID of this avaliacoes.
	 *
	 * @return the company ID of this avaliacoes
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this avaliacoes.
	 *
	 * @param companyId the company ID of this avaliacoes
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this avaliacoes.
	 *
	 * @return the group ID of this avaliacoes
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this avaliacoes.
	 *
	 * @param groupId the group ID of this avaliacoes
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this avaliacoes.
	 *
	 * @return the user ID of this avaliacoes
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this avaliacoes.
	 *
	 * @param userId the user ID of this avaliacoes
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this avaliacoes.
	 *
	 * @return the user uuid of this avaliacoes
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this avaliacoes.
	 *
	 * @param userUuid the user uuid of this avaliacoes
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this avaliacoes.
	 *
	 * @return the create date of this avaliacoes
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this avaliacoes.
	 *
	 * @param createDate the create date of this avaliacoes
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this avaliacoes.
	 *
	 * @return the modified date of this avaliacoes
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this avaliacoes.
	 *
	 * @param modifiedDate the modified date of this avaliacoes
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the avaliacoes ID of this avaliacoes.
	 *
	 * @return the avaliacoes ID of this avaliacoes
	 */
	public long getAvaliacoesId();

	/**
	 * Sets the avaliacoes ID of this avaliacoes.
	 *
	 * @param avaliacoesId the avaliacoes ID of this avaliacoes
	 */
	public void setAvaliacoesId(long avaliacoesId);

	/**
	 * Returns the descricao desafio ID of this avaliacoes.
	 *
	 * @return the descricao desafio ID of this avaliacoes
	 */
	public long getDescricaoDesafioId();

	/**
	 * Sets the descricao desafio ID of this avaliacoes.
	 *
	 * @param descricaoDesafioId the descricao desafio ID of this avaliacoes
	 */
	public void setDescricaoDesafioId(long descricaoDesafioId);

	/**
	 * Returns the tipo avaliador of this avaliacoes.
	 *
	 * @return the tipo avaliador of this avaliacoes
	 */
	@AutoEscape
	public String getTipoAvaliador();

	/**
	 * Sets the tipo avaliador of this avaliacoes.
	 *
	 * @param tipoAvaliador the tipo avaliador of this avaliacoes
	 */
	public void setTipoAvaliador(String tipoAvaliador);

	/**
	 * Returns the nome avaliador of this avaliacoes.
	 *
	 * @return the nome avaliador of this avaliacoes
	 */
	@AutoEscape
	public String getNomeAvaliador();

	/**
	 * Sets the nome avaliador of this avaliacoes.
	 *
	 * @param nomeAvaliador the nome avaliador of this avaliacoes
	 */
	public void setNomeAvaliador(String nomeAvaliador);

	/**
	 * Returns the observacoes avaliador of this avaliacoes.
	 *
	 * @return the observacoes avaliador of this avaliacoes
	 */
	@AutoEscape
	public String getObservacoesAvaliador();

	/**
	 * Sets the observacoes avaliador of this avaliacoes.
	 *
	 * @param observacoesAvaliador the observacoes avaliador of this avaliacoes
	 */
	public void setObservacoesAvaliador(String observacoesAvaliador);

	/**
	 * Returns the desempenho of this avaliacoes.
	 *
	 * @return the desempenho of this avaliacoes
	 */
	public int getDesempenho();

	/**
	 * Sets the desempenho of this avaliacoes.
	 *
	 * @param desempenho the desempenho of this avaliacoes
	 */
	public void setDesempenho(int desempenho);

	@Override
	public Avaliacoes cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}