/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.example.model.avaliacao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Funcionario service. Represents a row in the &quot;FOO_Funcionario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.example.model.avaliacao.model.impl.FuncionarioModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.example.model.avaliacao.model.impl.FuncionarioImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Funcionario
 * @generated
 */
@ProviderType
public interface FuncionarioModel extends BaseModel<Funcionario>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a funcionario model instance should use the {@link Funcionario} interface instead.
	 */

	/**
	 * Returns the primary key of this funcionario.
	 *
	 * @return the primary key of this funcionario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this funcionario.
	 *
	 * @param primaryKey the primary key of this funcionario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company ID of this funcionario.
	 *
	 * @return the company ID of this funcionario
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this funcionario.
	 *
	 * @param companyId the company ID of this funcionario
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this funcionario.
	 *
	 * @return the group ID of this funcionario
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this funcionario.
	 *
	 * @param groupId the group ID of this funcionario
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this funcionario.
	 *
	 * @return the user ID of this funcionario
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this funcionario.
	 *
	 * @param userId the user ID of this funcionario
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this funcionario.
	 *
	 * @return the user uuid of this funcionario
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this funcionario.
	 *
	 * @param userUuid the user uuid of this funcionario
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this funcionario.
	 *
	 * @return the create date of this funcionario
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this funcionario.
	 *
	 * @param createDate the create date of this funcionario
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this funcionario.
	 *
	 * @return the modified date of this funcionario
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this funcionario.
	 *
	 * @param modifiedDate the modified date of this funcionario
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the funcionario ID of this funcionario.
	 *
	 * @return the funcionario ID of this funcionario
	 */
	public long getFuncionarioId();

	/**
	 * Sets the funcionario ID of this funcionario.
	 *
	 * @param funcionarioId the funcionario ID of this funcionario
	 */
	public void setFuncionarioId(long funcionarioId);

	/**
	 * Returns the nome of this funcionario.
	 *
	 * @return the nome of this funcionario
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this funcionario.
	 *
	 * @param nome the nome of this funcionario
	 */
	public void setNome(String nome);

	/**
	 * Returns the email of this funcionario.
	 *
	 * @return the email of this funcionario
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this funcionario.
	 *
	 * @param email the email of this funcionario
	 */
	public void setEmail(String email);

	/**
	 * Returns the area atuacao of this funcionario.
	 *
	 * @return the area atuacao of this funcionario
	 */
	public int getAreaAtuacao();

	/**
	 * Sets the area atuacao of this funcionario.
	 *
	 * @param areaAtuacao the area atuacao of this funcionario
	 */
	public void setAreaAtuacao(int areaAtuacao);

	@Override
	public Funcionario cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}