/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.example.model.avaliacao.model.impl;

import br.com.example.model.avaliacao.model.Avaliacoes;
import br.com.example.model.avaliacao.service.AvaliacoesLocalServiceUtil;

/**
 * The extended model base implementation for the Avaliacoes service. Represents a row in the &quot;FOO_Avaliacoes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AvaliacoesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AvaliacoesImpl
 * @see Avaliacoes
 * @generated
 */
public abstract class AvaliacoesBaseImpl
	extends AvaliacoesModelImpl implements Avaliacoes {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a avaliacoes model instance should use the <code>Avaliacoes</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AvaliacoesLocalServiceUtil.addAvaliacoes(this);
		}
		else {
			AvaliacoesLocalServiceUtil.updateAvaliacoes(this);
		}
	}

}