/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.example.model.avaliacao.model.impl;

import br.com.example.model.avaliacao.model.Avaliacao;
import br.com.example.model.avaliacao.model.AvaliacaoModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Avaliacao service. Represents a row in the &quot;DESAFIO_Avaliacao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AvaliacaoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AvaliacaoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AvaliacaoImpl
 * @generated
 */
public class AvaliacaoModelImpl
	extends BaseModelImpl<Avaliacao> implements AvaliacaoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a avaliacao model instance should use the <code>Avaliacao</code> interface instead.
	 */
	public static final String TABLE_NAME = "DESAFIO_Avaliacao";

	public static final Object[][] TABLE_COLUMNS = {
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"avaliacaoId", Types.BIGINT},
		{"funcionarioId", Types.BIGINT}, {"dataAvaliacao", Types.TIMESTAMP},
		{"periodoDesafio", Types.INTEGER}, {"observacoesGerais", Types.VARCHAR},
		{"areaAtuacao", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("avaliacaoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("funcionarioId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataAvaliacao", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("periodoDesafio", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("observacoesGerais", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("areaAtuacao", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DESAFIO_Avaliacao (companyId LONG,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,avaliacaoId LONG not null primary key,funcionarioId LONG,dataAvaliacao DATE null,periodoDesafio INTEGER,observacoesGerais VARCHAR(75) null,areaAtuacao INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table DESAFIO_Avaliacao";

	public static final String ORDER_BY_JPQL =
		" ORDER BY avaliacao.avaliacaoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DESAFIO_Avaliacao.avaliacaoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AREAATUACAO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATAAVALIACAO_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FUNCIONARIOID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PERIODODESAFIO_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AVALIACAOID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AvaliacaoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _avaliacaoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAvaliacaoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _avaliacaoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Avaliacao.class;
	}

	@Override
	public String getModelClassName() {
		return Avaliacao.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Avaliacao, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Avaliacao, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Avaliacao, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Avaliacao)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Avaliacao, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Avaliacao, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Avaliacao)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Avaliacao, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Avaliacao, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Avaliacao, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Avaliacao, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Avaliacao, Object>>();

			attributeGetterFunctions.put("companyId", Avaliacao::getCompanyId);
			attributeGetterFunctions.put("groupId", Avaliacao::getGroupId);
			attributeGetterFunctions.put("userId", Avaliacao::getUserId);
			attributeGetterFunctions.put(
				"createDate", Avaliacao::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Avaliacao::getModifiedDate);
			attributeGetterFunctions.put(
				"avaliacaoId", Avaliacao::getAvaliacaoId);
			attributeGetterFunctions.put(
				"funcionarioId", Avaliacao::getFuncionarioId);
			attributeGetterFunctions.put(
				"dataAvaliacao", Avaliacao::getDataAvaliacao);
			attributeGetterFunctions.put(
				"periodoDesafio", Avaliacao::getPeriodoDesafio);
			attributeGetterFunctions.put(
				"observacoesGerais", Avaliacao::getObservacoesGerais);
			attributeGetterFunctions.put(
				"areaAtuacao", Avaliacao::getAreaAtuacao);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Avaliacao, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Avaliacao, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Avaliacao, ?>>();

			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Avaliacao, Long>)Avaliacao::setCompanyId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Avaliacao, Long>)Avaliacao::setGroupId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Avaliacao, Long>)Avaliacao::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Avaliacao, Date>)Avaliacao::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Avaliacao, Date>)Avaliacao::setModifiedDate);
			attributeSetterBiConsumers.put(
				"avaliacaoId",
				(BiConsumer<Avaliacao, Long>)Avaliacao::setAvaliacaoId);
			attributeSetterBiConsumers.put(
				"funcionarioId",
				(BiConsumer<Avaliacao, Long>)Avaliacao::setFuncionarioId);
			attributeSetterBiConsumers.put(
				"dataAvaliacao",
				(BiConsumer<Avaliacao, Date>)Avaliacao::setDataAvaliacao);
			attributeSetterBiConsumers.put(
				"periodoDesafio",
				(BiConsumer<Avaliacao, Integer>)Avaliacao::setPeriodoDesafio);
			attributeSetterBiConsumers.put(
				"observacoesGerais",
				(BiConsumer<Avaliacao, String>)Avaliacao::setObservacoesGerais);
			attributeSetterBiConsumers.put(
				"areaAtuacao",
				(BiConsumer<Avaliacao, Integer>)Avaliacao::setAreaAtuacao);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getAvaliacaoId() {
		return _avaliacaoId;
	}

	@Override
	public void setAvaliacaoId(long avaliacaoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_avaliacaoId = avaliacaoId;
	}

	@Override
	public long getFuncionarioId() {
		return _funcionarioId;
	}

	@Override
	public void setFuncionarioId(long funcionarioId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_funcionarioId = funcionarioId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFuncionarioId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("funcionarioId"));
	}

	@Override
	public Date getDataAvaliacao() {
		return _dataAvaliacao;
	}

	@Override
	public void setDataAvaliacao(Date dataAvaliacao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataAvaliacao = dataAvaliacao;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalDataAvaliacao() {
		return getColumnOriginalValue("dataAvaliacao");
	}

	@Override
	public int getPeriodoDesafio() {
		return _periodoDesafio;
	}

	@Override
	public void setPeriodoDesafio(int periodoDesafio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_periodoDesafio = periodoDesafio;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalPeriodoDesafio() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("periodoDesafio"));
	}

	@Override
	public String getObservacoesGerais() {
		if (_observacoesGerais == null) {
			return "";
		}
		else {
			return _observacoesGerais;
		}
	}

	@Override
	public void setObservacoesGerais(String observacoesGerais) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_observacoesGerais = observacoesGerais;
	}

	@Override
	public int getAreaAtuacao() {
		return _areaAtuacao;
	}

	@Override
	public void setAreaAtuacao(int areaAtuacao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_areaAtuacao = areaAtuacao;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalAreaAtuacao() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("areaAtuacao"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Avaliacao.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Avaliacao toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Avaliacao>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AvaliacaoImpl avaliacaoImpl = new AvaliacaoImpl();

		avaliacaoImpl.setCompanyId(getCompanyId());
		avaliacaoImpl.setGroupId(getGroupId());
		avaliacaoImpl.setUserId(getUserId());
		avaliacaoImpl.setCreateDate(getCreateDate());
		avaliacaoImpl.setModifiedDate(getModifiedDate());
		avaliacaoImpl.setAvaliacaoId(getAvaliacaoId());
		avaliacaoImpl.setFuncionarioId(getFuncionarioId());
		avaliacaoImpl.setDataAvaliacao(getDataAvaliacao());
		avaliacaoImpl.setPeriodoDesafio(getPeriodoDesafio());
		avaliacaoImpl.setObservacoesGerais(getObservacoesGerais());
		avaliacaoImpl.setAreaAtuacao(getAreaAtuacao());

		avaliacaoImpl.resetOriginalValues();

		return avaliacaoImpl;
	}

	@Override
	public Avaliacao cloneWithOriginalValues() {
		AvaliacaoImpl avaliacaoImpl = new AvaliacaoImpl();

		avaliacaoImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		avaliacaoImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		avaliacaoImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		avaliacaoImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		avaliacaoImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		avaliacaoImpl.setAvaliacaoId(
			this.<Long>getColumnOriginalValue("avaliacaoId"));
		avaliacaoImpl.setFuncionarioId(
			this.<Long>getColumnOriginalValue("funcionarioId"));
		avaliacaoImpl.setDataAvaliacao(
			this.<Date>getColumnOriginalValue("dataAvaliacao"));
		avaliacaoImpl.setPeriodoDesafio(
			this.<Integer>getColumnOriginalValue("periodoDesafio"));
		avaliacaoImpl.setObservacoesGerais(
			this.<String>getColumnOriginalValue("observacoesGerais"));
		avaliacaoImpl.setAreaAtuacao(
			this.<Integer>getColumnOriginalValue("areaAtuacao"));

		return avaliacaoImpl;
	}

	@Override
	public int compareTo(Avaliacao avaliacao) {
		long primaryKey = avaliacao.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Avaliacao)) {
			return false;
		}

		Avaliacao avaliacao = (Avaliacao)object;

		long primaryKey = avaliacao.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Avaliacao> toCacheModel() {
		AvaliacaoCacheModel avaliacaoCacheModel = new AvaliacaoCacheModel();

		avaliacaoCacheModel.companyId = getCompanyId();

		avaliacaoCacheModel.groupId = getGroupId();

		avaliacaoCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			avaliacaoCacheModel.createDate = createDate.getTime();
		}
		else {
			avaliacaoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			avaliacaoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			avaliacaoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		avaliacaoCacheModel.avaliacaoId = getAvaliacaoId();

		avaliacaoCacheModel.funcionarioId = getFuncionarioId();

		Date dataAvaliacao = getDataAvaliacao();

		if (dataAvaliacao != null) {
			avaliacaoCacheModel.dataAvaliacao = dataAvaliacao.getTime();
		}
		else {
			avaliacaoCacheModel.dataAvaliacao = Long.MIN_VALUE;
		}

		avaliacaoCacheModel.periodoDesafio = getPeriodoDesafio();

		avaliacaoCacheModel.observacoesGerais = getObservacoesGerais();

		String observacoesGerais = avaliacaoCacheModel.observacoesGerais;

		if ((observacoesGerais != null) && (observacoesGerais.length() == 0)) {
			avaliacaoCacheModel.observacoesGerais = null;
		}

		avaliacaoCacheModel.areaAtuacao = getAreaAtuacao();

		return avaliacaoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Avaliacao, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Avaliacao, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Avaliacao, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Avaliacao)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Avaliacao>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Avaliacao.class, ModelWrapper.class);

	}

	private long _companyId;
	private long _groupId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _avaliacaoId;
	private long _funcionarioId;
	private Date _dataAvaliacao;
	private int _periodoDesafio;
	private String _observacoesGerais;
	private int _areaAtuacao;

	public <T> T getColumnValue(String columnName) {
		Function<Avaliacao, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Avaliacao)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("avaliacaoId", _avaliacaoId);
		_columnOriginalValues.put("funcionarioId", _funcionarioId);
		_columnOriginalValues.put("dataAvaliacao", _dataAvaliacao);
		_columnOriginalValues.put("periodoDesafio", _periodoDesafio);
		_columnOriginalValues.put("observacoesGerais", _observacoesGerais);
		_columnOriginalValues.put("areaAtuacao", _areaAtuacao);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("companyId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("userId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("avaliacaoId", 32L);

		columnBitmasks.put("funcionarioId", 64L);

		columnBitmasks.put("dataAvaliacao", 128L);

		columnBitmasks.put("periodoDesafio", 256L);

		columnBitmasks.put("observacoesGerais", 512L);

		columnBitmasks.put("areaAtuacao", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Avaliacao _escapedModel;

}