/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.example.model.avaliacao.model.impl;

import br.com.example.model.avaliacao.model.Avaliacoes;
import br.com.example.model.avaliacao.model.AvaliacoesModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Avaliacoes service. Represents a row in the &quot;FOO_Avaliacoes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AvaliacoesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AvaliacoesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AvaliacoesImpl
 * @generated
 */
public class AvaliacoesModelImpl
	extends BaseModelImpl<Avaliacoes> implements AvaliacoesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a avaliacoes model instance should use the <code>Avaliacoes</code> interface instead.
	 */
	public static final String TABLE_NAME = "FOO_Avaliacoes";

	public static final Object[][] TABLE_COLUMNS = {
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"avaliacoesId", Types.BIGINT},
		{"descricaoDesafioId", Types.BIGINT}, {"tipoAvaliador", Types.VARCHAR},
		{"nomeAvaliador", Types.VARCHAR},
		{"observacoesAvaliador", Types.VARCHAR}, {"desempenho", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("avaliacoesId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("descricaoDesafioId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tipoAvaliador", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nomeAvaliador", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("observacoesAvaliador", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("desempenho", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FOO_Avaliacoes (companyId LONG,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,avaliacoesId LONG not null primary key,descricaoDesafioId LONG,tipoAvaliador VARCHAR(75) null,nomeAvaliador VARCHAR(75) null,observacoesAvaliador VARCHAR(75) null,desempenho INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table FOO_Avaliacoes";

	public static final String ORDER_BY_JPQL =
		" ORDER BY avaliacoes.avaliacoesId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FOO_Avaliacoes.avaliacoesId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AVALIACOESID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DESCRICAODESAFIOID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TIPOAVALIADOR_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AvaliacoesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _avaliacoesId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAvaliacoesId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _avaliacoesId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Avaliacoes.class;
	}

	@Override
	public String getModelClassName() {
		return Avaliacoes.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Avaliacoes, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Avaliacoes, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Avaliacoes, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Avaliacoes)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Avaliacoes, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Avaliacoes, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Avaliacoes)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Avaliacoes, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Avaliacoes, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Avaliacoes, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Avaliacoes, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Avaliacoes, Object>>();

			attributeGetterFunctions.put("companyId", Avaliacoes::getCompanyId);
			attributeGetterFunctions.put("groupId", Avaliacoes::getGroupId);
			attributeGetterFunctions.put("userId", Avaliacoes::getUserId);
			attributeGetterFunctions.put(
				"createDate", Avaliacoes::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Avaliacoes::getModifiedDate);
			attributeGetterFunctions.put(
				"avaliacoesId", Avaliacoes::getAvaliacoesId);
			attributeGetterFunctions.put(
				"descricaoDesafioId", Avaliacoes::getDescricaoDesafioId);
			attributeGetterFunctions.put(
				"tipoAvaliador", Avaliacoes::getTipoAvaliador);
			attributeGetterFunctions.put(
				"nomeAvaliador", Avaliacoes::getNomeAvaliador);
			attributeGetterFunctions.put(
				"observacoesAvaliador", Avaliacoes::getObservacoesAvaliador);
			attributeGetterFunctions.put(
				"desempenho", Avaliacoes::getDesempenho);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Avaliacoes, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Avaliacoes, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Avaliacoes, ?>>();

			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Avaliacoes, Long>)Avaliacoes::setCompanyId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<Avaliacoes, Long>)Avaliacoes::setGroupId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Avaliacoes, Long>)Avaliacoes::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Avaliacoes, Date>)Avaliacoes::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Avaliacoes, Date>)Avaliacoes::setModifiedDate);
			attributeSetterBiConsumers.put(
				"avaliacoesId",
				(BiConsumer<Avaliacoes, Long>)Avaliacoes::setAvaliacoesId);
			attributeSetterBiConsumers.put(
				"descricaoDesafioId",
				(BiConsumer<Avaliacoes, Long>)
					Avaliacoes::setDescricaoDesafioId);
			attributeSetterBiConsumers.put(
				"tipoAvaliador",
				(BiConsumer<Avaliacoes, String>)Avaliacoes::setTipoAvaliador);
			attributeSetterBiConsumers.put(
				"nomeAvaliador",
				(BiConsumer<Avaliacoes, String>)Avaliacoes::setNomeAvaliador);
			attributeSetterBiConsumers.put(
				"observacoesAvaliador",
				(BiConsumer<Avaliacoes, String>)
					Avaliacoes::setObservacoesAvaliador);
			attributeSetterBiConsumers.put(
				"desempenho",
				(BiConsumer<Avaliacoes, Integer>)Avaliacoes::setDesempenho);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getAvaliacoesId() {
		return _avaliacoesId;
	}

	@Override
	public void setAvaliacoesId(long avaliacoesId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_avaliacoesId = avaliacoesId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAvaliacoesId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("avaliacoesId"));
	}

	@Override
	public long getDescricaoDesafioId() {
		return _descricaoDesafioId;
	}

	@Override
	public void setDescricaoDesafioId(long descricaoDesafioId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descricaoDesafioId = descricaoDesafioId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDescricaoDesafioId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("descricaoDesafioId"));
	}

	@Override
	public String getTipoAvaliador() {
		if (_tipoAvaliador == null) {
			return "";
		}
		else {
			return _tipoAvaliador;
		}
	}

	@Override
	public void setTipoAvaliador(String tipoAvaliador) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tipoAvaliador = tipoAvaliador;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTipoAvaliador() {
		return getColumnOriginalValue("tipoAvaliador");
	}

	@Override
	public String getNomeAvaliador() {
		if (_nomeAvaliador == null) {
			return "";
		}
		else {
			return _nomeAvaliador;
		}
	}

	@Override
	public void setNomeAvaliador(String nomeAvaliador) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomeAvaliador = nomeAvaliador;
	}

	@Override
	public String getObservacoesAvaliador() {
		if (_observacoesAvaliador == null) {
			return "";
		}
		else {
			return _observacoesAvaliador;
		}
	}

	@Override
	public void setObservacoesAvaliador(String observacoesAvaliador) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_observacoesAvaliador = observacoesAvaliador;
	}

	@Override
	public int getDesempenho() {
		return _desempenho;
	}

	@Override
	public void setDesempenho(int desempenho) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_desempenho = desempenho;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Avaliacoes.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Avaliacoes toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Avaliacoes>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AvaliacoesImpl avaliacoesImpl = new AvaliacoesImpl();

		avaliacoesImpl.setCompanyId(getCompanyId());
		avaliacoesImpl.setGroupId(getGroupId());
		avaliacoesImpl.setUserId(getUserId());
		avaliacoesImpl.setCreateDate(getCreateDate());
		avaliacoesImpl.setModifiedDate(getModifiedDate());
		avaliacoesImpl.setAvaliacoesId(getAvaliacoesId());
		avaliacoesImpl.setDescricaoDesafioId(getDescricaoDesafioId());
		avaliacoesImpl.setTipoAvaliador(getTipoAvaliador());
		avaliacoesImpl.setNomeAvaliador(getNomeAvaliador());
		avaliacoesImpl.setObservacoesAvaliador(getObservacoesAvaliador());
		avaliacoesImpl.setDesempenho(getDesempenho());

		avaliacoesImpl.resetOriginalValues();

		return avaliacoesImpl;
	}

	@Override
	public Avaliacoes cloneWithOriginalValues() {
		AvaliacoesImpl avaliacoesImpl = new AvaliacoesImpl();

		avaliacoesImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		avaliacoesImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		avaliacoesImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		avaliacoesImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		avaliacoesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		avaliacoesImpl.setAvaliacoesId(
			this.<Long>getColumnOriginalValue("avaliacoesId"));
		avaliacoesImpl.setDescricaoDesafioId(
			this.<Long>getColumnOriginalValue("descricaoDesafioId"));
		avaliacoesImpl.setTipoAvaliador(
			this.<String>getColumnOriginalValue("tipoAvaliador"));
		avaliacoesImpl.setNomeAvaliador(
			this.<String>getColumnOriginalValue("nomeAvaliador"));
		avaliacoesImpl.setObservacoesAvaliador(
			this.<String>getColumnOriginalValue("observacoesAvaliador"));
		avaliacoesImpl.setDesempenho(
			this.<Integer>getColumnOriginalValue("desempenho"));

		return avaliacoesImpl;
	}

	@Override
	public int compareTo(Avaliacoes avaliacoes) {
		long primaryKey = avaliacoes.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Avaliacoes)) {
			return false;
		}

		Avaliacoes avaliacoes = (Avaliacoes)object;

		long primaryKey = avaliacoes.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Avaliacoes> toCacheModel() {
		AvaliacoesCacheModel avaliacoesCacheModel = new AvaliacoesCacheModel();

		avaliacoesCacheModel.companyId = getCompanyId();

		avaliacoesCacheModel.groupId = getGroupId();

		avaliacoesCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			avaliacoesCacheModel.createDate = createDate.getTime();
		}
		else {
			avaliacoesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			avaliacoesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			avaliacoesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		avaliacoesCacheModel.avaliacoesId = getAvaliacoesId();

		avaliacoesCacheModel.descricaoDesafioId = getDescricaoDesafioId();

		avaliacoesCacheModel.tipoAvaliador = getTipoAvaliador();

		String tipoAvaliador = avaliacoesCacheModel.tipoAvaliador;

		if ((tipoAvaliador != null) && (tipoAvaliador.length() == 0)) {
			avaliacoesCacheModel.tipoAvaliador = null;
		}

		avaliacoesCacheModel.nomeAvaliador = getNomeAvaliador();

		String nomeAvaliador = avaliacoesCacheModel.nomeAvaliador;

		if ((nomeAvaliador != null) && (nomeAvaliador.length() == 0)) {
			avaliacoesCacheModel.nomeAvaliador = null;
		}

		avaliacoesCacheModel.observacoesAvaliador = getObservacoesAvaliador();

		String observacoesAvaliador = avaliacoesCacheModel.observacoesAvaliador;

		if ((observacoesAvaliador != null) &&
			(observacoesAvaliador.length() == 0)) {

			avaliacoesCacheModel.observacoesAvaliador = null;
		}

		avaliacoesCacheModel.desempenho = getDesempenho();

		return avaliacoesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Avaliacoes, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Avaliacoes, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Avaliacoes, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Avaliacoes)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Avaliacoes>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Avaliacoes.class, ModelWrapper.class);

	}

	private long _companyId;
	private long _groupId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _avaliacoesId;
	private long _descricaoDesafioId;
	private String _tipoAvaliador;
	private String _nomeAvaliador;
	private String _observacoesAvaliador;
	private int _desempenho;

	public <T> T getColumnValue(String columnName) {
		Function<Avaliacoes, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Avaliacoes)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("avaliacoesId", _avaliacoesId);
		_columnOriginalValues.put("descricaoDesafioId", _descricaoDesafioId);
		_columnOriginalValues.put("tipoAvaliador", _tipoAvaliador);
		_columnOriginalValues.put("nomeAvaliador", _nomeAvaliador);
		_columnOriginalValues.put(
			"observacoesAvaliador", _observacoesAvaliador);
		_columnOriginalValues.put("desempenho", _desempenho);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("companyId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("userId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("avaliacoesId", 32L);

		columnBitmasks.put("descricaoDesafioId", 64L);

		columnBitmasks.put("tipoAvaliador", 128L);

		columnBitmasks.put("nomeAvaliador", 256L);

		columnBitmasks.put("observacoesAvaliador", 512L);

		columnBitmasks.put("desempenho", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Avaliacoes _escapedModel;

}