/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.example.model.avaliacao.model.impl;

import br.com.example.model.avaliacao.model.AvaliacaoDetalhe;
import br.com.example.model.avaliacao.service.AvaliacaoDetalheLocalServiceUtil;

/**
 * The extended model base implementation for the AvaliacaoDetalhe service. Represents a row in the &quot;DESAFIO_AvaliacaoDetalhe&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AvaliacaoDetalheImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AvaliacaoDetalheImpl
 * @see AvaliacaoDetalhe
 * @generated
 */
public abstract class AvaliacaoDetalheBaseImpl
	extends AvaliacaoDetalheModelImpl implements AvaliacaoDetalhe {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a avaliacao detalhe model instance should use the <code>AvaliacaoDetalhe</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AvaliacaoDetalheLocalServiceUtil.addAvaliacaoDetalhe(this);
		}
		else {
			AvaliacaoDetalheLocalServiceUtil.updateAvaliacaoDetalhe(this);
		}
	}

}