/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.example.model.avaliacao.model.impl;

import br.com.example.model.avaliacao.model.DescricaoDesafio;
import br.com.example.model.avaliacao.model.DescricaoDesafioModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DescricaoDesafio service. Represents a row in the &quot;FOO_DescricaoDesafio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DescricaoDesafioModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DescricaoDesafioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DescricaoDesafioImpl
 * @generated
 */
public class DescricaoDesafioModelImpl
	extends BaseModelImpl<DescricaoDesafio> implements DescricaoDesafioModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a descricao desafio model instance should use the <code>DescricaoDesafio</code> interface instead.
	 */
	public static final String TABLE_NAME = "FOO_DescricaoDesafio";

	public static final Object[][] TABLE_COLUMNS = {
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"descricaoDesafioId", Types.BIGINT},
		{"funcionarioId", Types.BIGINT}, {"dataAvaliacao", Types.TIMESTAMP},
		{"tipoDesafio", Types.INTEGER}, {"observacoesGerais", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("descricaoDesafioId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("funcionarioId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataAvaliacao", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("tipoDesafio", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("observacoesGerais", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FOO_DescricaoDesafio (companyId LONG,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,descricaoDesafioId LONG not null primary key,funcionarioId LONG,dataAvaliacao DATE null,tipoDesafio INTEGER,observacoesGerais VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table FOO_DescricaoDesafio";

	public static final String ORDER_BY_JPQL =
		" ORDER BY descricaoDesafio.descricaoDesafioId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FOO_DescricaoDesafio.descricaoDesafioId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATAAVALIACAO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DESCRICAODESAFIOID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FUNCIONARIOID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TIPODESAFIO_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DescricaoDesafioModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _descricaoDesafioId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDescricaoDesafioId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _descricaoDesafioId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DescricaoDesafio.class;
	}

	@Override
	public String getModelClassName() {
		return DescricaoDesafio.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DescricaoDesafio, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DescricaoDesafio, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DescricaoDesafio, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DescricaoDesafio)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DescricaoDesafio, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DescricaoDesafio, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DescricaoDesafio)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DescricaoDesafio, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DescricaoDesafio, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<DescricaoDesafio, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<DescricaoDesafio, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DescricaoDesafio, Object>>();

			attributeGetterFunctions.put(
				"companyId", DescricaoDesafio::getCompanyId);
			attributeGetterFunctions.put(
				"groupId", DescricaoDesafio::getGroupId);
			attributeGetterFunctions.put("userId", DescricaoDesafio::getUserId);
			attributeGetterFunctions.put(
				"createDate", DescricaoDesafio::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", DescricaoDesafio::getModifiedDate);
			attributeGetterFunctions.put(
				"descricaoDesafioId", DescricaoDesafio::getDescricaoDesafioId);
			attributeGetterFunctions.put(
				"funcionarioId", DescricaoDesafio::getFuncionarioId);
			attributeGetterFunctions.put(
				"dataAvaliacao", DescricaoDesafio::getDataAvaliacao);
			attributeGetterFunctions.put(
				"tipoDesafio", DescricaoDesafio::getTipoDesafio);
			attributeGetterFunctions.put(
				"observacoesGerais", DescricaoDesafio::getObservacoesGerais);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<DescricaoDesafio, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DescricaoDesafio, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<DescricaoDesafio, ?>>();

			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<DescricaoDesafio, Long>)
					DescricaoDesafio::setCompanyId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<DescricaoDesafio, Long>)
					DescricaoDesafio::setGroupId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<DescricaoDesafio, Long>)
					DescricaoDesafio::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<DescricaoDesafio, Date>)
					DescricaoDesafio::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<DescricaoDesafio, Date>)
					DescricaoDesafio::setModifiedDate);
			attributeSetterBiConsumers.put(
				"descricaoDesafioId",
				(BiConsumer<DescricaoDesafio, Long>)
					DescricaoDesafio::setDescricaoDesafioId);
			attributeSetterBiConsumers.put(
				"funcionarioId",
				(BiConsumer<DescricaoDesafio, Long>)
					DescricaoDesafio::setFuncionarioId);
			attributeSetterBiConsumers.put(
				"dataAvaliacao",
				(BiConsumer<DescricaoDesafio, Date>)
					DescricaoDesafio::setDataAvaliacao);
			attributeSetterBiConsumers.put(
				"tipoDesafio",
				(BiConsumer<DescricaoDesafio, Integer>)
					DescricaoDesafio::setTipoDesafio);
			attributeSetterBiConsumers.put(
				"observacoesGerais",
				(BiConsumer<DescricaoDesafio, String>)
					DescricaoDesafio::setObservacoesGerais);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getDescricaoDesafioId() {
		return _descricaoDesafioId;
	}

	@Override
	public void setDescricaoDesafioId(long descricaoDesafioId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descricaoDesafioId = descricaoDesafioId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDescricaoDesafioId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("descricaoDesafioId"));
	}

	@Override
	public long getFuncionarioId() {
		return _funcionarioId;
	}

	@Override
	public void setFuncionarioId(long funcionarioId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_funcionarioId = funcionarioId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFuncionarioId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("funcionarioId"));
	}

	@Override
	public Date getDataAvaliacao() {
		return _dataAvaliacao;
	}

	@Override
	public void setDataAvaliacao(Date dataAvaliacao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataAvaliacao = dataAvaliacao;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalDataAvaliacao() {
		return getColumnOriginalValue("dataAvaliacao");
	}

	@Override
	public int getTipoDesafio() {
		return _tipoDesafio;
	}

	@Override
	public void setTipoDesafio(int tipoDesafio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tipoDesafio = tipoDesafio;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalTipoDesafio() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("tipoDesafio"));
	}

	@Override
	public String getObservacoesGerais() {
		if (_observacoesGerais == null) {
			return "";
		}
		else {
			return _observacoesGerais;
		}
	}

	@Override
	public void setObservacoesGerais(String observacoesGerais) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_observacoesGerais = observacoesGerais;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DescricaoDesafio.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DescricaoDesafio toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DescricaoDesafio>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DescricaoDesafioImpl descricaoDesafioImpl = new DescricaoDesafioImpl();

		descricaoDesafioImpl.setCompanyId(getCompanyId());
		descricaoDesafioImpl.setGroupId(getGroupId());
		descricaoDesafioImpl.setUserId(getUserId());
		descricaoDesafioImpl.setCreateDate(getCreateDate());
		descricaoDesafioImpl.setModifiedDate(getModifiedDate());
		descricaoDesafioImpl.setDescricaoDesafioId(getDescricaoDesafioId());
		descricaoDesafioImpl.setFuncionarioId(getFuncionarioId());
		descricaoDesafioImpl.setDataAvaliacao(getDataAvaliacao());
		descricaoDesafioImpl.setTipoDesafio(getTipoDesafio());
		descricaoDesafioImpl.setObservacoesGerais(getObservacoesGerais());

		descricaoDesafioImpl.resetOriginalValues();

		return descricaoDesafioImpl;
	}

	@Override
	public DescricaoDesafio cloneWithOriginalValues() {
		DescricaoDesafioImpl descricaoDesafioImpl = new DescricaoDesafioImpl();

		descricaoDesafioImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		descricaoDesafioImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		descricaoDesafioImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		descricaoDesafioImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		descricaoDesafioImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		descricaoDesafioImpl.setDescricaoDesafioId(
			this.<Long>getColumnOriginalValue("descricaoDesafioId"));
		descricaoDesafioImpl.setFuncionarioId(
			this.<Long>getColumnOriginalValue("funcionarioId"));
		descricaoDesafioImpl.setDataAvaliacao(
			this.<Date>getColumnOriginalValue("dataAvaliacao"));
		descricaoDesafioImpl.setTipoDesafio(
			this.<Integer>getColumnOriginalValue("tipoDesafio"));
		descricaoDesafioImpl.setObservacoesGerais(
			this.<String>getColumnOriginalValue("observacoesGerais"));

		return descricaoDesafioImpl;
	}

	@Override
	public int compareTo(DescricaoDesafio descricaoDesafio) {
		long primaryKey = descricaoDesafio.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DescricaoDesafio)) {
			return false;
		}

		DescricaoDesafio descricaoDesafio = (DescricaoDesafio)object;

		long primaryKey = descricaoDesafio.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DescricaoDesafio> toCacheModel() {
		DescricaoDesafioCacheModel descricaoDesafioCacheModel =
			new DescricaoDesafioCacheModel();

		descricaoDesafioCacheModel.companyId = getCompanyId();

		descricaoDesafioCacheModel.groupId = getGroupId();

		descricaoDesafioCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			descricaoDesafioCacheModel.createDate = createDate.getTime();
		}
		else {
			descricaoDesafioCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			descricaoDesafioCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			descricaoDesafioCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		descricaoDesafioCacheModel.descricaoDesafioId = getDescricaoDesafioId();

		descricaoDesafioCacheModel.funcionarioId = getFuncionarioId();

		Date dataAvaliacao = getDataAvaliacao();

		if (dataAvaliacao != null) {
			descricaoDesafioCacheModel.dataAvaliacao = dataAvaliacao.getTime();
		}
		else {
			descricaoDesafioCacheModel.dataAvaliacao = Long.MIN_VALUE;
		}

		descricaoDesafioCacheModel.tipoDesafio = getTipoDesafio();

		descricaoDesafioCacheModel.observacoesGerais = getObservacoesGerais();

		String observacoesGerais = descricaoDesafioCacheModel.observacoesGerais;

		if ((observacoesGerais != null) && (observacoesGerais.length() == 0)) {
			descricaoDesafioCacheModel.observacoesGerais = null;
		}

		return descricaoDesafioCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DescricaoDesafio, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DescricaoDesafio, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DescricaoDesafio, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DescricaoDesafio)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DescricaoDesafio>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DescricaoDesafio.class, ModelWrapper.class);

	}

	private long _companyId;
	private long _groupId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _descricaoDesafioId;
	private long _funcionarioId;
	private Date _dataAvaliacao;
	private int _tipoDesafio;
	private String _observacoesGerais;

	public <T> T getColumnValue(String columnName) {
		Function<DescricaoDesafio, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DescricaoDesafio)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("descricaoDesafioId", _descricaoDesafioId);
		_columnOriginalValues.put("funcionarioId", _funcionarioId);
		_columnOriginalValues.put("dataAvaliacao", _dataAvaliacao);
		_columnOriginalValues.put("tipoDesafio", _tipoDesafio);
		_columnOriginalValues.put("observacoesGerais", _observacoesGerais);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("companyId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("userId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("descricaoDesafioId", 32L);

		columnBitmasks.put("funcionarioId", 64L);

		columnBitmasks.put("dataAvaliacao", 128L);

		columnBitmasks.put("tipoDesafio", 256L);

		columnBitmasks.put("observacoesGerais", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DescricaoDesafio _escapedModel;

}