/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.example.model.avaliacao.model.impl;

import br.com.example.model.avaliacao.model.DescricaoDesafio;
import br.com.example.model.avaliacao.service.DescricaoDesafioLocalServiceUtil;

/**
 * The extended model base implementation for the DescricaoDesafio service. Represents a row in the &quot;FOO_DescricaoDesafio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DescricaoDesafioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DescricaoDesafioImpl
 * @see DescricaoDesafio
 * @generated
 */
public abstract class DescricaoDesafioBaseImpl
	extends DescricaoDesafioModelImpl implements DescricaoDesafio {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a descricao desafio model instance should use the <code>DescricaoDesafio</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DescricaoDesafioLocalServiceUtil.addDescricaoDesafio(this);
		}
		else {
			DescricaoDesafioLocalServiceUtil.updateDescricaoDesafio(this);
		}
	}

}